# TD — Construire une mini « NewsAPI » avec des flux RSS (Python)
**Objectif :** récupérer des articles depuis plusieurs flux **RSS/Atom**, normaliser les données, filtrer par mots-clés et dates, dédoublonner et exporter.

- Durée indicative : 3h
- Format : Notebook Jupyter

## 0) Installation et imports

Exécutez la cellule suivante pour installer les dépendances (une fois par environnement).

In [69]:
!pip -q install feedparser pandas python-dateutil tqdm

In [70]:
import re
from datetime import datetime, timezone
from dateutil import parser as dateparser

import feedparser
import pandas as pd
from tqdm import tqdm

pd.set_option("display.max_colwidth", 120)

## 1) Choisir des flux RSS/Atom

### Exercice 1 — Trouver des flux
1. Trouvez **au moins 5 flux RSS/Atom francophones** (journaux, radios, TV, sites institutionnels, blogs tech, etc.).
2. Collez les URL dans la liste `RSS_FEEDS`.

**Astuce :** souvent, un site propose une page « RSS » / « Flux » / « Syndication ».

In [72]:
RSS_FEEDS = [
    #list des flux
]

## 2) Parser un flux RSS/Atom de manière robuste

Un flux RSS/Atom n’est pas toujours homogène : certaines entrées ont `published`, d’autres `updated`, parfois la date est absente.

### Exercice 2 — Compléter `safe_parse_date`
Complétez la fonction pour retourner un `datetime` (timezone-aware si possible) ou `None`.

In [73]:
def safe_parse_date(entry):
    """Essaie de récupérer une date de publication depuis une entrée RSS/Atom.

    Retourne:
        datetime | None
    """
    # TODO: implémenter une stratégie robuste:
    # 1) essayer entry.get("published")
    # 2) sinon entry.get("updated")
    # 3) sinon None
    # Hint: dateparser.parse(...)
    return None

## 3) Récupérer un flux et le convertir en lignes normalisées

### Exercice 3 — Écrire `fetch_feed`
Écrivez une fonction qui prend une URL de flux et retourne une liste de dictionnaires, avec les clés suivantes :

- `source` (nom du média / titre du flux)
- `feed_url`
- `title`
- `url`
- `summary`
- `published_at`

**Bonus :** enlever le HTML dans le résumé.

In [75]:
def strip_html(text):
    if not text:
        return ""
    # TODO: enlever les tags HTML et réduire les espaces
    return text

def fetch_feed(url, source_name=None):
    # TODO: parser le flux avec feedparser.parse(url)
    # TODO: extraire un titre de flux d.feed.get("title")
    # TODO: parcourir d.entries et construire les dicts normalisés
    return []

## 4) Agréger plusieurs flux dans un DataFrame

### Exercice 4 — Construire `df`
1. Bouclez sur `RSS_FEEDS`
2. Agrégez toutes les lignes dans une liste
3. Construisez un DataFrame `df`
4. Affichez les 10 premières lignes

In [77]:
all_rows = []
# TODO: compléter la boucle

df = pd.DataFrame(all_rows)
df.head(10)

Empty DataFrame
Columns: []
Index: []

## 5) Normaliser et nettoyer les données

### Exercice 5 — Écrire `normalize`
- Convertir `published_at` en datetime pandas (UTC)
- Remplacer les NaN par chaîne vide sur `title`, `summary`, `url`, `source`
- Supprimer les lignes sans URL ou sans titre (au choix)

In [79]:
def normalize(df):
    df = df.copy()
    # TODO: conversions + nettoyage
    return df

dfn = normalize(df)
dfn.info()
dfn.head(10)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101 entries, 0 to 100
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   source        101 non-null    object
 1   feed_url      101 non-null    object
 2   title         101 non-null    object
 3   url           101 non-null    object
 4   summary       101 non-null    object
 5   published_at  101 non-null    object
dtypes: object(6)
memory usage: 4.9+ KB

,source,feed_url,title,url,summary,published_at
0,Le Monde.fr - Actualités et Infos en France et dans le monde,https://www.lemonde.fr/rss/une.xml,"EN DIRECT, Iran : les Etats-Unis ne mènent pas « un exercice de construction de démocratie », dit le ministre améric...",https://www.lemonde.fr/international/live/2026/03/02/en-direct-iran-teheran-contrairement-aux-etats-unis-s-est-prepa...,"Le ministre de la défense américain a déclaré que les Etats-Unis « iront aussi loin que nécessaire », n’écartant pas...",2026-03-02 14:16:39+01:00
1,Le Monde.fr - Actualités et Infos en France et dans le monde,https://www.lemonde.fr/rss/une.xml,"Clément Therme, historien : « La mort d’Ali Khamenei met à nu l’impasse d’un système »",https://www.lemonde.fr/idees/article/2026/03/02/clement-therme-historien-la-mort-d-ali-khamenei-met-a-nu-l-impasse-d...,"En donnant la priorité à la lutte idéologique transnationale sur les intérêts intérieurs du pays, le régime iranien ...",2026-03-02 14:00:13+01:00
2,Le Monde.fr - Actualités et Infos en France et dans le monde,https://www.lemonde.fr/rss/une.xml,"EN DIRECT, discours d’Emmanuel Macron sur le nucléaire : suivez l’allocution du chef de l’Etat sur la dissuasion fra...",https://www.lemonde.fr/international/live/2026/03/02/en-direct-discours-d-emmanuel-macron-sur-le-nucleaire-suivez-l-...,"Depuis l’île Longue à Brest, où sont stationnés les quatre sous-marins nucléaires lanceurs d’engins français, le pré...",2026-03-02 13:30:05+01:00
3,Le Monde.fr - Actualités et Infos en France et dans le monde,https://www.lemonde.fr/rss/une.xml,"Hugo, 30 ans, pilote de ligne, 6 000 euros par mois : « Je vis mon rêve, après avoir galéré »",https://www.lemonde.fr/campus/article/2026/03/02/hugo-30-ans-pilote-de-ligne-6-000-euros-par-mois-je-vis-mon-reve-ap...,"« La bonne paye ». Chaque semaine, « Le Monde » parle d’argent avec les jeunes, de leurs factures, leur loyer, leurs...",2026-03-02 06:00:22+01:00
4,Le Monde.fr - Actualités et Infos en France et dans le monde,https://www.lemonde.fr/rss/une.xml,"Raphaël Glucksmann estime que Jean-Luc Mélenchon, qui a plaisanté sur la prononciation de son nom, joue avec « les p...",https://www.lemonde.fr/politique/article/2026/03/02/raphael-glucksmann-estime-que-jean-luc-melenchon-qui-a-plaisante...,"« On ne joue pas (…) sur des noms à consonance juive ou à consonance étrangère », a dit l’eurodéputé après avoir été...",2026-03-02 09:35:51+01:00
5,Le Monde.fr - Actualités et Infos en France et dans le monde,https://www.lemonde.fr/rss/une.xml,"La hausse des droits d’inscription à l’université, l’« éléphant » dans le débat sur leur financement",https://www.lemonde.fr/idees/article/2026/03/02/la-hausse-des-droits-d-inscription-a-l-universite-l-elephant-dans-le...,L’hypothèse d’une hausse des frais d’inscription pour les étudiants pourrait s’imposer à l’issue du dialogue ouvert ...,2026-03-02 12:00:13+01:00
6,Le Monde.fr - Actualités et Infos en France et dans le monde,https://www.lemonde.fr/rss/une.xml,"EN DIRECT, guerre en Ukraine : les dernières informations",https://www.lemonde.fr/international/live/2026/03/02/en-direct-guerre-en-ukraine-les-dernieres-informations_6668763_...,"Le président ukrainien, Volodymyr Zelensky, a déclaré qu’il espérait toujours qu’une nouvelle rencontre Ukraine - Ru...",2026-03-02 14:39:24+01:00
7,Le Monde.fr - Actualités et Infos en France et dans le monde,https://www.lemonde.fr/rss/une.xml,"« Une augmentation de salaire hors norme » pour Slawomir Krupa, patron de la Société générale, qui gagne désormais 2...",https://www.lemonde.fr/economie/article/2026/03/02/a-la-societe-generale-une-augmentation-de-salaire-hors-norme-pour...,"Le conseil d’administration de la banque a décidé d’augmenter de 45 % le salaire fixe de son directeur général, la j...",2026-03-02 11:30:08+01:00
8,Le Monde.fr - Actualités et Infos en France et dans le monde,https://www.lemonde.fr/rss/une.xml,Quel temps fait-il pour la saison ? Retrouvez « La Météo du Climat » du jour dans votre ville,https://www.lemonde.fr/climat/meteo/,"Consultez les prévisions météo dans votre ville ou votre région, associées à des données historiques mettant en lumi...",2025-11-21 16:27:51+01:00
9,Le Monde.fr - Actualités et Infos en France et dans le monde,https://www.lemonde.fr/rss/une.xml,Municipales à Créteil : Laurent Cathala brigue un neuvième mandat,https://www.lemonde.fr/politique/article/2026/03/02/municipales-a-creteil-laurent-cathala-brigue-un-neuvieme-mandat_...,"A 80 ans, le maire de la préfecture du Val-de-Marne se lance confiant dans une nouvelle campagne municipale. Bien qu...",2026-03-02 13:00:00+01:00

## 6) Filtrage thématique (mots-clés)

On veut quelque chose qui ressemble à `q=...` de NewsAPI.

### Exercice 6 — Implémenter `filter_by_keywords`
La fonction doit accepter une liste de mots-clés et garder les lignes où **le titre ou le résumé** contient au moins un mot-clé (insensible à la casse).

In [81]:
def filter_by_keywords(df, keywords):
    if not keywords:
        return df.copy()
    pattern = "|".join(re.escape(k) for k in keywords)
    mask = (
        df["title"].str.contains(pattern, case=False, na=False) |
        df["summary"].str.contains(pattern, case=False, na=False)
    )
    return df[mask].copy()

keywords = #TODO
df_ai = #TODO
df_ai[["published_at", "source", "title", "url"]].head(20)

,published_at,source,title,url
0,2026-03-02 13:16:39+00:00,Le Monde.fr - Actualités et Infos en France et dans le monde,"EN DIRECT, Iran : les Etats-Unis ne mènent pas « un exercice de construction de démocratie », dit le ministre améric...",https://www.lemonde.fr/international/live/2026/03/02/en-direct-iran-teheran-contrairement-aux-etats-unis-s-est-prepa...
1,2026-03-02 13:00:13+00:00,Le Monde.fr - Actualités et Infos en France et dans le monde,"Clément Therme, historien : « La mort d’Ali Khamenei met à nu l’impasse d’un système »",https://www.lemonde.fr/idees/article/2026/03/02/clement-therme-historien-la-mort-d-ali-khamenei-met-a-nu-l-impasse-d...
2,2026-03-02 12:30:05+00:00,Le Monde.fr - Actualités et Infos en France et dans le monde,"EN DIRECT, discours d’Emmanuel Macron sur le nucléaire : suivez l’allocution du chef de l’Etat sur la dissuasion fra...",https://www.lemonde.fr/international/live/2026/03/02/en-direct-discours-d-emmanuel-macron-sur-le-nucleaire-suivez-l-...
3,2026-03-02 05:00:22+00:00,Le Monde.fr - Actualités et Infos en France et dans le monde,"Hugo, 30 ans, pilote de ligne, 6 000 euros par mois : « Je vis mon rêve, après avoir galéré »",https://www.lemonde.fr/campus/article/2026/03/02/hugo-30-ans-pilote-de-ligne-6-000-euros-par-mois-je-vis-mon-reve-ap...
4,2026-03-02 08:35:51+00:00,Le Monde.fr - Actualités et Infos en France et dans le monde,"Raphaël Glucksmann estime que Jean-Luc Mélenchon, qui a plaisanté sur la prononciation de son nom, joue avec « les p...",https://www.lemonde.fr/politique/article/2026/03/02/raphael-glucksmann-estime-que-jean-luc-melenchon-qui-a-plaisante...
5,2026-03-02 11:00:13+00:00,Le Monde.fr - Actualités et Infos en France et dans le monde,"La hausse des droits d’inscription à l’université, l’« éléphant » dans le débat sur leur financement",https://www.lemonde.fr/idees/article/2026/03/02/la-hausse-des-droits-d-inscription-a-l-universite-l-elephant-dans-le...
6,2026-03-02 13:39:24+00:00,Le Monde.fr - Actualités et Infos en France et dans le monde,"EN DIRECT, guerre en Ukraine : les dernières informations",https://www.lemonde.fr/international/live/2026/03/02/en-direct-guerre-en-ukraine-les-dernieres-informations_6668763_...
7,2026-03-02 10:30:08+00:00,Le Monde.fr - Actualités et Infos en France et dans le monde,"« Une augmentation de salaire hors norme » pour Slawomir Krupa, patron de la Société générale, qui gagne désormais 2...",https://www.lemonde.fr/economie/article/2026/03/02/a-la-societe-generale-une-augmentation-de-salaire-hors-norme-pour...
8,2025-11-21 15:27:51+00:00,Le Monde.fr - Actualités et Infos en France et dans le monde,Quel temps fait-il pour la saison ? Retrouvez « La Météo du Climat » du jour dans votre ville,https://www.lemonde.fr/climat/meteo/
9,2026-03-02 12:00:00+00:00,Le Monde.fr - Actualités et Infos en France et dans le monde,Municipales à Créteil : Laurent Cathala brigue un neuvième mandat,https://www.lemonde.fr/politique/article/2026/03/02/municipales-a-creteil-laurent-cathala-brigue-un-neuvieme-mandat_...
10,2026-03-02 04:45:02+00:00,Le Monde.fr - Actualités et Infos en France et dans le monde,IA : une start-up de San Francisco veut bâtir un « scientifique artificiel » pour « guérir toutes les maladies »,https://www.lemonde.fr/economie/article/2026/03/02/ia-une-start-up-de-san-francisco-veut-batir-un-scientifique-artif...
11,2026-03-02 12:49:10+00:00,Le Monde.fr - Actualités et Infos en France et dans le monde,"Les prisons françaises comptaient 86 645 détenus au 1ᵉʳ février 2026, leur plus haut niveau selon les chiffres du go...",https://www.lemonde.fr/societe/article/2026/03/02/les-prisons-francaises-comptaient-86-645-detenus-au-1-fevrier-2026...
12,2026-03-02 13:30:00+00:00,Le Monde.fr - Actualités et Infos en France et dans le monde,Comment Xiaomi est devenu le principal concurrent d’Apple et Samsung sur le marché des smartphones,https://www.lemonde.fr/economie/article/2026/03/02/comment-xiaomi-s-est-installe-comme-le-principal-concurrent-d-app...
13,2026-03-02 10:35:31+00:00,Le Monde.fr - Actualités et Infos en France et dans le monde,Un nouveau tableau de Rembrandt découvert au Rijksmuseum,https://www.lemonde.fr/culture/article/2026/03/02/decouverte-d-un-nouveau-tableau-de-rembrandt-au-rijksmuseum_666922...
14,2026-03-02 13:00:01+00:00,Le Monde.fr - Actualités et Infos en France et dans le monde,"Dans « Gachiakuta », les déchets ont une âme mais les humains peu de cœur",https://www.lemonde.fr/culture/article/2026/03/02/dans-gachiakuta-les-dechets-ont-une-ame-mais-les-humains-peu-de-c-...
15,2026-03-02 11:04:27+00:00,Le Monde.fr - Actualités et Infos en France et dans le monde,"Quatre mois après l’ouragan Melissa, les pays des Caraïbes face à des « dommages persistants »",https://www.lemonde.fr/planete/article/2026/03/02/quatre-mois-apres-l-ouragan-melissa-les-pays-des-caraibes-face-a-d...
16,2026-03-01 19:29:04+00:00,Le Monde.fr - Actualités et Infos en France et dans le monde,"Entre l’Afghanistan et le Pakistan, les affrontements se poursuivent, des explosions entendues à Kaboul",https://www.lemonde.fr/international/article/2026/03/01/entre-l-afghanistan-et-le-pakistan-les-affrontements-se-pour...
17,2026-03-02 13:49:02+00:00,Franceinfo - Les Titres,"Guerre au Moyen-Orient : ""Ce n'est que le début"", le conflit va ""perdurer"", prévient le chef d'état-major interarmée...",https://www.franceinfo.fr/monde/conflit-israel-iran/direct-guerre-entre-les-etats-unis-israel-et-l-iran-l-etat-hebre...
18,2026-03-02 09:37:14+00:00,Franceinfo - Les Titres,"Au moins 31 morts, riposte puis ""offensive"" contre le Hezbollah, ""jours de combats"" à venir… Ce que l'on sait des fr...",https://www.franceinfo.fr/monde/iran/guerre-entre-les-etats-unis-israel-et-l-iran/au-moins-31-morts-riposte-puis-off...
19,2026-03-02 11:03:42+00:00,Franceinfo - Les Titres,"Au moins 555 personnes sont mortes en Iran depuis le début de la guerre avec Israël et les Etats-Unis, affirme le Cr...",https://www.franceinfo.fr/monde/iran/guerre-entre-les-etats-unis-israel-et-l-iran/au-moins-555-personnes-sont-mortes...

## 7) Filtrage par dates

### Exercice 7 — Implémenter `filter_by_date`
On filtre entre `start` (inclus) et `end` (exclus).

In [83]:
def filter_by_date(df, start=None, end=None):
    # TODO
    return df

# Exemple: janvier 2026
df_ai_jan = filter_by_date(df_ai, start="2026-01-01", end="2026-02-01")
df_ai_jan.sort_values("published_at", ascending=False).head(20)

,source,feed_url,title,url,summary,published_at
85,Libération,https://www.liberation.fr/arc/outboundfeeds/rss-all/?outputType=xml,"«Papaoutai», IAM ou Aznavour… Les reprises de musique à l’IA, entre accords et désaccords",https://www.liberation.fr/culture/musique/papaoutai-iam-ou-aznavour-les-reprises-de-musique-a-lia-entre-accords-et-d...,"Depuis sa publication en décembre, une reprise à l’intelligence artificielle du tube de Stromae cumule plus de 70 mi...",2026-03-02 04:33:00+00:00

## 8) Export (TXT + CSV + JSON)

### Exercice 8 - Exporter comme dans ton script NewsAPI
Exporter en `txt` (format libre), puis aussi en `csv` et `json`.

Critères :
- Inclure `source`, `title`, `summary`, `published_at`, `url`
- Un séparateur clair entre articles

In [87]:
def export_txt(df, path):
    # TODO
    pass

# TODO: appeler export_txt, puis to_csv / to_json

## 9) Bonus — Scoring de pertinence

### Exercice 9 — Score d’occurrence
Créer une colonne `score` = nombre d’occurrences des mots-clés dans titre + résumé.
Afficher le top 20 par score.

Bonus : pondérer le titre (ex: titre compte double).

In [89]:
def add_score(df, keywords):
    # TODO
    return df

df_scored = add_score(df_ai_jan, keywords)
df_scored.sort_values(["score", "published_at"], ascending=[False, False]).head(20)[
    ["score", "published_at", "source", "title", "url"]
]

KeyError: 'score'

## 10) Bonus — Statistiques rapides

### Exercice 11 — Articles par source
- Faire un `value_counts()` sur `source`
- Afficher un bar chart (matplotlib)

In [ ]:
# TODO
# dfn_source = df_ai_jan["source"].value_counts()
# dfn_source.head(20)

# import matplotlib.pyplot as plt
# dfn_source.head(15).plot(kind="bar")
# plt.title("Nombre d'articles (filtrés) par source")
# plt.show()